carproject:
  hmac-key: your_hmac_key_value
  allowlist:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: carproject
    username: root
    password: root