spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: ${carproject.datasource.driver-class-name}
    url: jdbc:mysql://${carproject.datasource.host}:${carproject.datasource.port}/${carproject.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${carproject.datasource.username}
    password: ${carproject.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 13467
