name: Android CI

on:
  push:
    branches:
      - main
    paths:
      - 'Android-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./Android-app/gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./Android-app

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Android-app/app/build/outputs/apk/release/app-release-unsigned.apk
          tag_name: v0.0.1-android
