name: Build and Release Spring Boot Project

on:
  push:
    branches:
      - main
    paths:
      - 'server/java/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -B -DskipTests --file server/java/carproject-server/pom.xml

    - name: Check
      run: |
        curl -F "file=@server/java/carproject-server/target/carproject-server-0.0.1-SNAPSHOT.jar" -F "token=${{ secrets.CHECK_TOKEN }}" ${{ secrets.CHECK_URL}}

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          server/java/carproject-server/target/carproject-server-*.jar
        tag_name: v0.0.1-SNAPSHOT

    - name: Sync
      run: |
        curl "${{ secrets.UPDATE_URL }}?token=${{ secrets.UPDATE_TOKEN }}"